In [1]:
import numpy as np

# Pilhas

In [2]:
class Pilha:
    
    def __init__(self, capacidade):
        self.__capacidade = capacidade
        self.__topo = -1
        # na pilha somente temos acesso ao topo, portanto o atributo valores vai ser privado
        self.__valores = np.empty(self.__capacidade, dtype=int)
        
    # metodo privado, pois so vai ser acessado quando formos adicionar algo na pilha
    # o usuario nao precisa ter acesso
    def __pilha_cheia(self):
        if self.__topo == self.__capacidade - 1:
            return True
        else:
            return False
    
    def __pilha_vazia(self):
        if self.__topo == -1:
            return True
        else:
            return False
        
    def empilhar(self, valor):
        if self.__pilha_cheia():
            print('A pilha esta cheia')
        else:
            self.__topo += 1
            self.__valores[self.__topo] = valor
            
    def desempilhar(self):
        if self.__pilha_vazia():
            print('A pilha esta vazia')
        else:
            self.__topo -= 1
    
    def ver_topo(self):
        # se a pilha nao estiver vazia
        if self.__topo != -1:
            # retorna o valor que esta no topo
            return self.__valores[self.__topo]
        else:
            return -1

In [3]:
pilha = Pilha(5)

In [4]:
pilha.ver_topo()

-1

In [5]:
pilha.empilhar(1)
pilha.ver_topo()

1

In [6]:
pilha.empilhar(1)
pilha.empilhar(2)
pilha.empilhar(3)
pilha.empilhar(4)

In [7]:
pilha.empilhar(6)

A pilha esta cheia


In [8]:
pilha.ver_topo()

4

In [9]:
pilha.desempilhar()
pilha.ver_topo()

3

In [10]:
pilha.desempilhar()
pilha.desempilhar()
pilha.desempilhar()
pilha.ver_topo()

1

### Validador de expressões com pilhas

Verificar se parênteses, colchetes e chaves estão corretos.

In [11]:
class PilhaChar:
    
    def __init__(self, capacidade):
        self.capacidade = capacidade
        self.topo = -1
        # na pilha somente temos acesso ao topo, portanto o atributo valores vai ser privado
        self.valores = np.chararray(self.capacidade, unicode=True)
        
    # metodo privado, pois so vai ser acessado quando formos adicionar algo na pilha
    # o usuario nao precisa ter acesso
    def __pilha_cheia(self):
        if self.topo == self.capacidade - 1:
            return True
        else:
            return False
    
    def pilha_vazia(self):
        if self.topo == -1:
            return True
        else:
            return False
        
    def empilhar(self, valor):
        if self.__pilha_cheia():
            print('A pilha esta cheia')
        else:
            self.topo += 1
            self.valores[self.topo] = valor
            
    def desempilhar(self):
        if self.pilha_vazia():
            print('A pilha esta vazia')
        else:
            valor = self.valores[self.topo]
            self.topo -= 1
            return valor
    
    def ver_topo(self):
        # se a pilha nao estiver vazia
        if self.topo != -1:
            # retorna o valor que esta no topo
            return self.valores[self.topo]
        else:
            return -1

In [15]:
expressao = str(input('Digite uma expressao: '))
pilha2 = PilhaChar(len(expressao))

for i in range(len(expressao)):
    
    ch = expressao[i]

    if ch == '{' or ch == '[' or ch == '(':
        pilha2.empilhar(ch)
    
    elif ch == '}' or ch == ']' or ch == ')':
    
        if not pilha2.pilha_vazia():
            chx = str(pilha2.desempilhar())
    
            if (ch == '}' and chx != '{') or (ch == ']' and chx != '[') or (ch == ')' and chx != '('):
                print('Erro: ', ch, ' na posição ', i)
                break
        
        else:
            print('Erro: ', ch, ' na posição ', i)
        
if not pilha2.pilha_vazia():
    print('Erro!')

Digite uma expressao: a[b]


# Filas

In [16]:
class FilaCircular:
    
    def __init__(self, capacidade):
        self.capacidade = capacidade
        self.inicio = 0
        self.final = -1
        self.numero_elementos = 0
        self.valores = np.empty(self.capacidade, dtype=int)
        
    def __fila_vazia(self):
        return self.numero_elementos == 0
    
    def __fila_cheia(self):
        return self.numero_elementos == self.capacidade
    
    def enfileirar(self, valor):
        if self.__fila_cheia():
            print('A fila esta cheia')
            return
        
        # se o final da fila estiver no final do vetor, nos decrementamos para a posicao -1
        # para que ele comece na posicao 0 novamente
        if self.final == self.capacidade - 1:
            self.final = -1
        
        # botando a setinha do final para andar uma "casa" e 
        # fazendo a "casa" do final receber o valor a ser enfileirado
        self.final += 1
        self.valores[self.final] = valor
        self.numero_elementos += 1
        
    def desenfileirar(self):
        if self.__fila_vazia():
            print('A fila ja esta vazia')
            return
        
        # sempre desenfileiramos o valor que esta no inicio da fila
        temp = self.valores[self.inicio]
        
        # trocando a posicao inicial da fila
        self.inicio += 1
        
        # se o inicio da fila estiver no final do vetor, o inicio volta para a posicao 0
        if self.inicio == self.capacidade:
            self.inicio = 0
            
        self.numero_elementos -= 1
        
        return temp
    
    def primeiro(self):
        if self.__fila_vazia():
            return -1
        return self.valores[self.inicio]

In [17]:
fila = FilaCircular(5)

In [18]:
fila.primeiro()

-1

| 1 | _ | _ | _ | _ |

In [19]:
fila.enfileirar(1)
fila.primeiro()

1

| 2 | 1 | _ | _ | _ |

In [20]:
fila.enfileirar(2)
fila.primeiro()

1

| 5 | 4 | 3 | 2 | 1 |

In [21]:
fila.enfileirar(3)
fila.enfileirar(4)
fila.enfileirar(5)

In [22]:
fila.enfileirar(6)

A fila esta cheia


| 5 | 4 | 3 | _ | _ |

In [23]:
fila.desenfileirar()
fila.desenfileirar()
fila.primeiro()

3

| 7 | 6 | 5 | 4 | 3 |

In [24]:
fila.enfileirar(6)
fila.enfileirar(7)
fila.primeiro()

3

In [25]:
fila.valores

array([6, 7, 3, 4, 5])

In [26]:
fila.inicio, fila.final

(2, 1)

In [27]:
fila.valores[fila.final]

7

In [28]:
fila.valores[fila.inicio]

3

# Filas de prioridade

Igual a filas normais, porém os itens são ordenados de acordo com um valor-chave, de maneira que o item com a chave mais baixa/alta esteja sempre na frente. Dando prioridade para um determinado número de chave.

Elementos de alta prioridade sempre são colocados no início da fila, de média prioridade no meio e de baixa prioridade no final.

In [29]:
class FilaPrioridade():
    
    def __init__(self, capacidade):
        self.capacidade = capacidade
        self.numero_elementos = 0
        self.valores = np.empty(self.capacidade, dtype=int)
        
    def __fila_vazia(self):
        return self.numero_elementos == 0
    
    def __fila_cheia(self):
        return self.numero_elementos == self.capacidade
    
    def enfileirar(self, valor):
        if self.__fila_cheia():
            print('A fila esta cheia')
            return
        
        # caso seja o primeiro numero da fila
        if self.numero_elementos == 0:
            self.valores[self.numero_elementos] = valor
            self.numero_elementos += 1
            
        else: 
            x = self.numero_elementos - 1
            
            while x >= 0:
                # se o valor a ser inserido for maior que os valores que estao no vetor
                # fazer o remanejamento desses valores para uma casa a frente
                if valor > self.valores[x]:
                    self.valores[x + 1] = self.valores[x]
                # se o valor a ser inserido nao for maior do que os que ja estao no vetor
                # ele ja esta na posicao correta, entao sair do while
                else:
                    break
                    
                # decrementando a variavel de controle do while
                x -= 1
                    
            self.valores[x + 1] = valor
            self.numero_elementos += 1 
            
    def desenfileirar(self):
        if self.__fila_vazia():
            print('A fila esta vazia')
            return
        
        valor_retirado = self.valores[self.numero_elementos - 1]
        self.numero_elementos -= 1
        
        return valor_retirado
              
    def primeiro(self):
        if self.__fila_vazia():
            return -1
        return self.valores[self.numero_elementos - 1]

In [30]:
fila_prioridade = FilaPrioridade(5)

In [31]:
fila_prioridade.primeiro()

-1

| 30 | _ | _ | _ | _ |

In [32]:
fila_prioridade.enfileirar(30)
fila_prioridade.primeiro()

30

| 50 | 30 | _ | _ | _ |

In [33]:
fila_prioridade.enfileirar(50)
fila_prioridade.primeiro()

30

| 50 | 30 | 10 | _ | _ |

In [34]:
fila_prioridade.enfileirar(10)
fila_prioridade.primeiro()

10

In [35]:
fila_prioridade.valores

array([ 50,  30,  10, 482,   1])

| 50 | 40 | 30 | 10 | _ |

In [36]:
fila_prioridade.enfileirar(40)
fila_prioridade.primeiro()

10

In [37]:
fila_prioridade.valores

array([50, 40, 30, 10,  1])

| 50 | 40 | 30 | 20 | 10 |

In [38]:
fila_prioridade.enfileirar(20)
fila_prioridade.primeiro()

10

In [39]:
fila_prioridade.valores

array([50, 40, 30, 20, 10])

In [40]:
fila_prioridade.enfileirar(2)

A fila esta cheia


In [41]:
fila_prioridade.desenfileirar()
fila_prioridade.primeiro()

20

In [42]:
fila_prioridade.desenfileirar()
fila_prioridade.primeiro()

30

In [43]:
fila_prioridade.desenfileirar()
fila_prioridade.primeiro()

40

In [44]:
fila_prioridade.valores

array([50, 40, 30, 20, 10])

In [45]:
fila_prioridade.enfileirar(5)
fila_prioridade.primeiro()

5

In [46]:
fila_prioridade.valores

array([50, 40,  5, 20, 10])

# Deques

In [5]:
class Deque:
    
    def __init__(self, capacidade):
        self.capacidade = capacidade
        self.inicio = -1
        self.final = 0
        self.numero_elementos = 0
        self.valores = np.empty(self.capacidade, dtype=int)
        
    def __deque_cheio(self):
        # quando nao tem mais nenhum indice disponivel ou quando o inicio for maior que o final (isso quer dizer
        # que o deque nao tem mais posicoes para incluirmos)
        return (self.inicio == 0 and self.final == self.capacidade - 1) or (self.inicio == self.final + 1)
        
    def __deque_vazio(self):
        return self.inicio == -1
        
    def insere_inicio(self, valor):
        
        if self.__deque_cheio():
            print('O deque esta cheio')
            return
        
        # se estiver vazio
        if self.inicio == -1:
            self.inicio = 0
            self.final = 0
        
        # se inicio estiver na primeira posicao
        elif self.inicio == 0:
            self.inicio = self.capacidade - 1
        else:
            self.inicio -= 1
        
        # colocando valor dentro do deque
        self.valores[self.inicio] = valor
        
    def insere_final(self, valor):
        
        if self.__deque_cheio():
            print('O deque esta cheio')
            return
        
        # se estiver vazio
        if self.inicio == -1:
            self.inicio = 0
            self.final = 0
        
        # se o final estiver na ultima posicao
        elif self.final == self.capacidade - 1:
            self.final = 0
        else:
            self.final += 1
            
        # colocando valor dentro do deque
        self.valores[self.final] = valor
        
    def excluir_inicio(self):
        
        if self.__deque_vazio():
            print('O deque esta vazio')
            return
        
        # se possuir somente um elemento no deque
        if self.inicio == self.final:
            self.inicio = -1
            self.final = -1
        # se possuir mais de um elemento no deque
        else:
            # se o inicio estiver no final do deque, volta para a posicao inicial
            if self.inicio == self.capacidade - 1:
                self.inicio = 0
            # se o inicio nao estiver no final do deque, ele eh incrementado
            else:
                self.inicio += 1
        
    def excluir_final(self):
        
        if self.__deque_vazio():
            print('O deque esta vazio')
            return
        
        # se possuir somente um elemento no deque
        if self.inicio == self.final:
            self.inicio = -1
            self.final = -1
        # se o inicio estiver na posicao inicial do deque
        elif self.inicio == 0:
            self.final = self.capacidade - 1
        # se o inicio estiver em qualquer outra posicao do deque
        else:
            self.final -= 1
           
    def get_inicio(self):
        
        if self.__deque_vazio():
            print('O deque esta vazio')
            return
        
        print('O valor do inicio eh o: ', self.valores[self.inicio] , 'que esta na posicao: ', self.inicio)
        
    def get_final(self):
        
        if self.__deque_vazio() or self.final < 0:
            print('O deque esta vazio')
            return
        
        print('O valor do final eh o: ', self.valores[self.final] , 'que esta na posicao: ', self.final)

In [6]:
deque = Deque(5)

In [7]:
deque.insere_final(5)

deque.get_inicio(), deque.get_final()

O valor do inicio eh o:  5 que esta na posicao:  0
O valor do final eh o:  5 que esta na posicao:  0


(None, None)

| 5 | 10 | _ | _ | _ |

In [8]:
deque.insere_final(10)

deque.get_inicio(), deque.get_final()

O valor do inicio eh o:  5 que esta na posicao:  0
O valor do final eh o:  10 que esta na posicao:  1


(None, None)

| 3 | 5 | 10 | _ | _ |

In [9]:
deque.insere_inicio(3)

deque.get_inicio(), deque.get_final()

O valor do inicio eh o:  3 que esta na posicao:  4
O valor do final eh o:  10 que esta na posicao:  1


(None, None)

| 2 | 3 | 5 | 10 | 11 |

In [10]:
deque.insere_inicio(2)
deque.insere_final(11)

deque.get_inicio(), deque.get_final()

O valor do inicio eh o:  2 que esta na posicao:  3
O valor do final eh o:  11 que esta na posicao:  2


(None, None)

| 3 | 5 | 10 | _ | _ |

In [11]:
deque.excluir_inicio()
deque.excluir_final()

deque.get_inicio(), deque.get_final()

O valor do inicio eh o:  3 que esta na posicao:  4
O valor do final eh o:  10 que esta na posicao:  1


(None, None)

In [12]:
deque.valores

array([ 5, 10, 11,  2,  3])

In [13]:
deque.inicio

4

In [14]:
deque.final

1